title: Javi Ballester CV & Portfolio
email: javimixet@gmail.com
description: Online printable CV and Portfolio - Javier Ballester Tomas. # > # this means to ignore newlines until "baseurl:"
  
# baseurl: "" # the subpath of your site, e.g. /blog
url: "http://javimixet.github.io"
# github_username:  javimixet

# Project URL
#permalink: /:title/

markdown: kramdown